export const DEFAULT_SETTINGS = {
  cafe_name: "Amrogn Chicken",
  tagline: "Home of Authentic Shawarma in Addis Ababa",
  hero_title: "Home of Authentic Shawarma",
  hero_subtitle:
    "Amrogn Chicken, 4 Kilo branch on the ground floor of Ambassador Mall. Famous chicken shawarma, fire-grilled and roasted chicken, tandoor mofo and crispy fried chicken. Dine in, take away, or scan your table QR and order in English or Amharic.",
  hero_bg_image: "/images/menu/fried-hero.jpg",
  phone: "097 895 7070",
  address: "Ambassador Mall, Ground Floor, 4 Kilo, Addis Ababa, Ethiopia",
  plus_code: "2QM5+XFX Addis Ababa",
  lat: "9.0349875",
  lng: "38.7587344",
  google_rating: "4.1",
  google_review_count: "195",
  opening_hours: "Open Daily 10:00 AM - 10:00 PM",
  about_title: "Why Addis Runs on Amrogn Chicken",
  about_description:
    "Established in 2018, Amrogn Chicken introduced Addis Ababa to shawarma and grew into the city's home of chicken: shawarma carved off the spit, fire-grilled and roasted chicken that falls off the bone, tandoor mofo and light crispy fried chicken. At the busy 4 Kilo branch in Ambassador Mall you scan your table QR, order from your phone in English or Amharic, and the order goes straight to the kitchen, the juice station and the cashier.",
  announcement:
    "🍗 Welcome to Amrogn Chicken, 4 Kilo (Ambassador Mall)! Scan the QR on your table to order, no waiting for a waiter.",
  logo_url: "",
  receipt_enabled: "true",
  // Group 9 (print-queue workflow): how the cashier screen works.
  //   "print-queue" = Amrogn workflow, the cashier's job is ONE click per order
  //                   (key it into the EFD/POS, print, tap PRINTED). Payment
  //                   tracking lives in the EFD/POS, not in this app. Waiters
  //                   close bills by tapping "Table cleared".
  //   "full"        = full-payment mode, cashier records payment methods and
  //                   marks bills Paid (for future branches without an EFD).
  cashier_mode: "print-queue",
  admin_password: "amrogn2026",
};

export const DEFAULT_TABLES = Array.from({ length: 10 }, (_, i) => ({
  name: `Table ${i + 1}`,
  sortOrder: i + 1,
}));

export const DEFAULT_CATEGORY_ROUTING: Record<string, "barista" | "kitchen" | "juice"> = {
  // everything chicken-tier goes to the KITCHEN (the chef/grill line)
  shawarma: "kitchen",
  chicken: "kitchen",
  burgers: "kitchen",
  sides: "kitchen",
  combos: "kitchen",
  "family-meals": "kitchen",
  specials: "kitchen",
  // Amrogn 4 Kilo runs ONE beverage crew: the Juice & Cold Drinks station
  // handles soft drinks AND fresh juices (the engine key stays "juice").
  drinks: "juice",
  "soft-drinks": "juice",
  "hot-drinks": "juice",
  // fresh juices go to the same Juice & Cold Drinks station
  "fresh-juices": "juice",
  juices: "juice",
  // legacy slugs from the engine's first cafe customer, kept so old rows route
  "ethiopian-traditional-meals": "kitchen",
  sandwich: "kitchen",
  "snack-and-wrap": "kitchen",
  burger: "kitchen",
  pasta: "kitchen",
  pizza: "kitchen",
  rice: "kitchen",
  salad: "kitchen",
  soup: "kitchen",
  "pastry-and-cakes": "kitchen",
  "sides-meals": "kitchen",
  "main-meal": "kitchen",
};

export const DEFAULT_STAFF = [
  { name: "Dawit (Waiter)", role: "waiter", pin: "1111" },
  { name: "Selam (Waiter)", role: "waiter", pin: "3333" },
  { name: "Hanna (Cashier)", role: "cashier", pin: "2222" },
  { name: "Girma (Kitchen)", role: "kitchen", pin: "5555" },
  { name: "Meron (Juice & Drinks)", role: "juice", pin: "6666" },
];

export const DEFAULT_CATEGORIES = [
  { id: 1, name: "All Items", slug: "all", icon: "Utensils", sortOrder: 0 },
  { id: 2, name: "Shawarma", slug: "shawarma", icon: "Sandwich", sortOrder: 1 },
  { id: 3, name: "Chicken", slug: "chicken", icon: "Drumstick", sortOrder: 2 },
  { id: 4, name: "Chicken Burgers", slug: "burgers", icon: "Hamburger", sortOrder: 3 },
  { id: 5, name: "Sides", slug: "sides", icon: "Popcorn", sortOrder: 4 },
  { id: 6, name: "Combos", slug: "combos", icon: "UtensilsCrossed", sortOrder: 5 },
  { id: 7, name: "Family Meals", slug: "family-meals", icon: "Users", sortOrder: 6 },
  { id: 8, name: "Drinks", slug: "drinks", icon: "CupSoda", sortOrder: 7 },
  { id: 9, name: "Fresh Juices", slug: "fresh-juices", icon: "Citrus", sortOrder: 8 },
  { id: 10, name: "Specials", slug: "specials", icon: "Flame", sortOrder: 9 },
];

/**
 * Cafe-era default categories the chicken menu replaced. Kept here so the seed
 * never re-inserts them, the legacy-slug migration never re-creates them, and a
 * one-time prune knows exactly which rows to delete. The owner can still add
 * any category manually later.
 */
export const REMOVED_DEFAULT_CATEGORY_SLUGS = [
  "ethiopian-traditional-meals",
  "sandwich",
  "snack-and-wrap",
  "juices",
  "hot-drinks",
  "soft-drinks",
  "pastry-and-cakes",
  "soup",
  "pasta",
  "pizza",
  "salad",
  "rice",
  "burger",
];

// Legacy slug -> new category slug mapping (migration keeps existing items visible)
export const CATEGORY_SLUG_MAP: Record<string, string> = {
  shawarma: "shawarma",
  wraps: "shawarma",
  wrap: "shawarma",
  sandwiches: "shawarma",
  sandwich: "shawarma",
  "snack-and-wrap": "shawarma",
  snacks: "sides",
  "fast-food": "combos",
  burger: "burgers",
  burgers: "burgers",
  // every old hot meal becomes a chicken line
  food: "chicken",
  meals: "chicken",
  "ethiopian-meals": "chicken",
  "ethiopian-traditional-meals": "chicken",
  traditional: "chicken",
  "main-meal": "chicken",
  "sides-meals": "sides",
  rice: "chicken",
  pizza: "chicken",
  pasta: "chicken",
  salads: "sides",
  salad: "sides",
  soups: "sides",
  soup: "sides",
  // drinks
  "signature-coffee": "drinks",
  coffee: "drinks",
  "hot-coffee": "drinks",
  "macchiato-coffee": "drinks",
  "cold-drinks": "drinks",
  "fresh-drinks": "fresh-juices",
  smoothies: "fresh-juices",
  juices: "fresh-juices",
  "soft-drinks": "drinks",
  // desserts fold into sides
  pastries: "sides",
  bakery: "sides",
  cakes: "sides",
  desserts: "sides",
  dessert: "sides",
};

export const DEFAULT_MENU_ITEMS = [
  // ───────────────────────── Shawarma ─────────────────────────
  {
    id: 101,
    name: "Chicken Shawarma",
    category: "shawarma",
    price: 285,
    description:
      "Our signature. Marinated chicken carved off the spit with garlic sauce and fresh vegetables, wrapped in soft bread. The shawarma that made Amrogn famous.",
    imageUrl: "/images/menu/shawarma-special.jpg",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "Menu Highlight, Most Ordered, House Famous",
    prepTime: "5 min",
    badge: "Most Ordered",
    sortOrder: 1,
  },
  {
    id: 102,
    name: "Special Shawarma",
    category: "shawarma",
    price: 380,
    description:
      "Loaded with extra chicken, cheese, crispy fries inside and our house sauces, wrapped and grilled until the bread is lightly crisp.",
    imageUrl: "/images/menu/shawarma.jpg",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "Menu Highlight, Extra Loaded",
    prepTime: "7 min",
    badge: "Customer Favorite",
    sortOrder: 2,
  },
  {
    id: 103,
    name: "Shawarma Plate",
    category: "shawarma",
    price: 560,
    description:
      "Carved shawarma chicken served open on a plate with golden fries, fresh salad and a big side of garlic sauce.",
    imageUrl: "/images/menu/shawarma-plate.jpg",
    isPopular: false,
    isAvailable: true,
    dietaryTags: "Shareable, Served with Fries",
    prepTime: "10 min",
    badge: "Plate",
    sortOrder: 3,
  },
  // ───────────────────────── Chicken ─────────────────────────
  {
    id: 104,
    name: "Crispy Fried Chicken (2 pcs)",
    category: "chicken",
    price: 380,
    description:
      "Fried chicken at its best: juicy and tender inside, light and crispy on the outside, fried golden to order.",
    imageUrl: "/images/menu/fried.jpg",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "Crispy, Fried to Order",
    prepTime: "10 min",
    badge: "Crispy",
    sortOrder: 4,
  },
  {
    id: 105,
    name: "Chicken Fajita",
    category: "chicken",
    price: 490,
    description:
      "Sizzling grilled chicken strips with peppers and onions, served with soft tortilla bread and dips.",
    imageUrl: "/images/menu/fajita.jpg",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "On the Grill, Sizzling",
    prepTime: "12 min",
    badge: "From the Grill",
    sortOrder: 5,
  },
  {
    id: 106,
    name: "Chicken Kabsa",
    category: "chicken",
    price: 540,
    description:
      "Oven-baked spiced chicken over a mountain of fragrant slow-cooked rice with toasted nuts and raisins.",
    imageUrl: "/images/menu/kabsa.jpg",
    isPopular: false,
    isAvailable: true,
    dietaryTags: "Oven Baked, Spiced Rice",
    prepTime: "15 min",
    badge: "Oven Baked",
    sortOrder: 6,
  },
  {
    id: 107,
    name: "Grilled Quarter Leg",
    category: "chicken",
    price: 640,
    description:
      "Our famous fire-grilled chicken quarter in a smoky marinade, served with bread and house sauce.",
    imageUrl: "/images/menu/grilled-quarter.jpg",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "Fire Grilled, Smoky",
    prepTime: "15 min",
    badge: "Fire Grilled",
    sortOrder: 7,
  },
  {
    id: 108,
    name: "Chicken Mofo Quarter Leg",
    category: "chicken",
    price: 730,
    description:
      "Mofo is a chicken that is perfectly scored, marinated and grilled in the tandoor: tender inside, lightly charred outside.",
    imageUrl: "/images/menu/mofo-quarter.jpg",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "Tandoor Grilled, Marinated",
    prepTime: "15 min",
    badge: "Tandoor",
    sortOrder: 8,
  },
  {
    id: 109,
    name: "Roasted Chicken Half",
    category: "chicken",
    price: 730,
    description:
      "Half a chicken slow roasted until it falls off the bone and melts in your mouth, with sides for one.",
    imageUrl: "/images/menu/roasted-half.jpg",
    isPopular: false,
    isAvailable: true,
    dietaryTags: "Slow Roasted, Juicy",
    prepTime: "20 min",
    badge: "Roasted",
    sortOrder: 9,
  },
  {
    id: 110,
    name: "Grilled Double Quarter Leg",
    category: "chicken",
    price: 1280,
    description:
      "Two fire-grilled quarter legs with our smoky flavor. Worth sharing with family and friends.",
    imageUrl: "/images/menu/grilled-double.jpg",
    isPopular: false,
    isAvailable: true,
    dietaryTags: "Fire Grilled, Shareable",
    prepTime: "18 min",
    badge: "Double",
    sortOrder: 10,
  },
  {
    id: 111,
    name: "Chicken Mofo Double Quarter Leg",
    category: "chicken",
    price: 1450,
    description:
      "Double portion of tandoor-grilled mofo, scored and marinated overnight, for a very hungry table.",
    imageUrl: "/images/menu/mofo-double.jpg",
    isPopular: false,
    isAvailable: true,
    dietaryTags: "Tandoor Grilled, Double Portion",
    prepTime: "20 min",
    badge: "Double",
    sortOrder: 11,
  },
  {
    id: 112,
    name: "Roasted Chicken Full",
    category: "chicken",
    price: 1450,
    description:
      "A whole chicken slow roasted to golden, juicy perfection with sides for the table. The best roasted chicken in town.",
    imageUrl: "/images/menu/roasted-full.jpg",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "Menu Highlight, Whole Chicken, Feeds the Table",
    prepTime: "25 min",
    badge: "House Classic",
    sortOrder: 12,
  },
  // ───────────────────────── Burgers ─────────────────────────
  {
    id: 113,
    name: "Crispy Chicken Burger",
    category: "burgers",
    price: 320,
    description:
      "Crunchy fried chicken fillet with lettuce, tomato and house mayo in a soft bun, served with fries.",
    imageUrl: "/images/menu/burger.jpg",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "Crispy Fillet, Served with Fries",
    prepTime: "10 min",
    badge: "Popular",
    sortOrder: 13,
  },
  {
    id: 114,
    name: "Double Chicken Burger",
    category: "burgers",
    price: 420,
    description:
      "Double stacked crispy chicken with cheese and our special sauce in a toasted bun, served with fries.",
    imageUrl: "/images/menu/burger-2.jpg",
    isPopular: false,
    isAvailable: true,
    dietaryTags: "Double Stack, Cheese",
    prepTime: "12 min",
    badge: "Double",
    sortOrder: 14,
  },
  // ───────────────────────── Sides ─────────────────────────
  {
    id: 115,
    name: "Golden French Fries",
    category: "sides",
    price: 150,
    description:
      "Crispy golden fries served hot with tomato ketchup and our house chili dip.",
    imageUrl: "/images/menu/fries.jpg",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "Crispy, Vegetarian",
    prepTime: "7 min",
    badge: "Side",
    sortOrder: 15,
  },
  {
    id: 116,
    name: "Chicken Nuggets (6 pcs)",
    category: "sides",
    price: 260,
    description:
      "Bite-sized crispy chicken nuggets, golden outside and tender inside, with a choice of dipping sauce.",
    imageUrl: "/images/menu/nuggets.jpg",
    isPopular: false,
    isAvailable: true,
    dietaryTags: "Crispy, Kid Favorite",
    prepTime: "8 min",
    badge: "6 Pieces",
    sortOrder: 16,
  },
  // ───────────────────────── Combos ─────────────────────────
  {
    id: 117,
    name: "Fried Chicken Combo",
    category: "combos",
    price: 480,
    description:
      "2 pieces of crispy fried chicken, golden fries and a cold soft drink. The quick Amrogn lunch.",
    imageUrl: "/images/menu/combo-meal.jpg",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "Complete Meal, Drink Included",
    prepTime: "12 min",
    badge: "Best Value",
    sortOrder: 17,
  },
  {
    id: 118,
    name: "Shawarma Combo",
    category: "combos",
    price: 450,
    description:
      "A regular chicken shawarma with a portion of crispy fries and a soft drink.",
    imageUrl: "/images/menu/shawarma-3.jpg",
    isPopular: false,
    isAvailable: true,
    dietaryTags: "Complete Meal, Drink Included",
    prepTime: "10 min",
    badge: "Combo",
    sortOrder: 18,
  },
  // ───────────────────────── Family meals ─────────────────────────
  {
    id: 119,
    name: "Fried Chicken Bucket (8 pcs)",
    category: "family-meals",
    price: 1350,
    description:
      "Eight pieces of our crispy golden fried chicken in the Amrogn bucket, made for sharing.",
    imageUrl: "/images/menu/family-bucket.jpg",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "Feeds 3-4, Bucket",
    prepTime: "20 min",
    badge: "Family",
    sortOrder: 19,
  },
  {
    id: 120,
    name: "Crispy Family Box",
    category: "family-meals",
    price: 1100,
    description:
      "6 pieces of crispy fried chicken with two large portions of fries, packed for the family table.",
    imageUrl: "/images/menu/fried-basket.jpg",
    isPopular: false,
    isAvailable: true,
    dietaryTags: "Feeds 3, Two Fries",
    prepTime: "18 min",
    badge: "Family",
    sortOrder: 20,
  },
  {
    id: 121,
    name: "Shawarma Family Box",
    category: "family-meals",
    price: 1450,
    description:
      "Four chicken shawarmas, a large plate of fries and four soft drinks for the whole table.",
    imageUrl: "/images/menu/shawarma-plate.jpg",
    isPopular: false,
    isAvailable: true,
    dietaryTags: "Feeds 4, 4 Drinks",
    prepTime: "15 min",
    badge: "Feeds 4",
    sortOrder: 21,
  },
  // ───────────────────────── Drinks ─────────────────────────
  {
    id: 122,
    name: "Soft Drink (Coca, Sprite, Fanta)",
    category: "drinks",
    price: 70,
    description: "Ice-cold canned soft drink. Choose Coca-Cola, Sprite or Fanta.",
    imageUrl: "/images/menu/soda.jpg",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "Ice Cold",
    prepTime: "2 min",
    badge: "",
    sortOrder: 22,
  },
  {
    id: 123,
    name: "Mineral Water",
    category: "drinks",
    price: 50,
    description: "Bottled mineral water, served cold.",
    imageUrl: "/images/menu/soda.jpg",
    isPopular: false,
    isAvailable: true,
    dietaryTags: "Cold",
    prepTime: "1 min",
    badge: "",
    sortOrder: 23,
  },
  // ───────────────────────── Fresh juices ─────────────────────────
  {
    id: 124,
    name: "Fresh Mango / Orange Juice",
    category: "fresh-juices",
    price: 180,
    description: "Freshly blended ripe mango or squeezed orange, made when you order.",
    imageUrl: "/images/menu/juice.jpg",
    isPopular: true,
    isAvailable: true,
    dietaryTags: "100% Fresh, No Sugar Added",
    prepTime: "5 min",
    badge: "Fresh",
    sortOrder: 24,
  },
  {
    id: 125,
    name: "Avocado-Mango Spris",
    category: "fresh-juices",
    price: 200,
    description: "Layered avocado and mango puree, the classic Addis spris blended fresh.",
    imageUrl: "/images/menu/juice.jpg",
    isPopular: false,
    isAvailable: true,
    dietaryTags: "Layered, 100% Fruit",
    prepTime: "7 min",
    badge: "Spris",
    sortOrder: 25,
  },
  // ───────────────────────── Specials ─────────────────────────
  {
    id: 126,
    name: "Spicy Crispy Chicken Burger",
    category: "specials",
    price: 360,
    description:
      "Our crispy chicken burger kicked up with spicy glaze, jalapenos and chili mayo, with fries.",
    imageUrl: "/images/menu/burger-2.jpg",
    isPopular: false,
    isAvailable: true,
    dietaryTags: "Spicy, Limited Special",
    prepTime: "10 min",
    badge: "Hot Special",
    sortOrder: 26,
  },
  {
    id: 127,
    name: "Cheesy Special Shawarma",
    category: "specials",
    price: 450,
    description:
      "The special shawarma with extra melted cheese and grilled chicken, lightly toasted until the cheese pulls.",
    imageUrl: "/images/menu/shawarma-3.jpg",
    isPopular: false,
    isAvailable: true,
    dietaryTags: "Extra Cheese, Limited Special",
    prepTime: "8 min",
    badge: "Cheesy",
    sortOrder: 27,
  },
];

export const DEFAULT_REVIEWS = [
  {
    customerName: "Afom K.F.S",
    rating: 5,
    reviewText:
      "My second time visiting this place and both times the food was yummy. The place is always busy, it is the spot to eat at 4 Kilo. Totally recommended.",
    reviewDate: "2 months ago",
    isApproved: true,
    isVerified: true,
  },
  {
    customerName: "Dave DaCosta",
    rating: 4,
    reviewText:
      "This is definitely the place in Addis for chicken. The shawarma and roasted chicken are worth the wait. The food is worth it, every time.",
    reviewDate: "3 months ago",
    isApproved: true,
    isVerified: true,
  },
  {
    customerName: "Ermias Alemayehu",
    rating: 4,
    reviewText:
      "Amazing food, one of the best chicken dishes in Addis, from the shawarma to the mofo. Kudos to the chefs preparing the tasty food.",
    reviewDate: "4 months ago",
    isApproved: true,
    isVerified: true,
  },
  {
    customerName: "Mohammed Ahmed",
    rating: 5,
    reviewText:
      "Good food and better than the other branches by a mile. Simply one of the best spots in Addis if you are craving chicken.",
    reviewDate: "5 months ago",
    isApproved: true,
    isVerified: true,
  },
];

export const DEFAULT_GALLERY = [
  {
    title: "Famous Chicken Shawarma",
    category: "Shawarma",
    imageUrl: "/images/menu/shawarma-special.jpg",
    caption: "Carved off the spit, wrapped with garlic sauce and fresh vegetables.",
    sortOrder: 1,
  },
  {
    title: "Crispy Fried Chicken",
    category: "Fried",
    imageUrl: "/images/menu/fried-hero.jpg",
    caption: "Juicy inside, light and crispy outside, fried to order.",
    sortOrder: 2,
  },
  {
    title: "Fire-Grilled Chicken",
    category: "Grilled",
    imageUrl: "/images/menu/grilled-quarter.jpg",
    caption: "Our famous fire-grilled quarter leg in a smoky marinade.",
    sortOrder: 3,
  },
  {
    title: "Chicken Fajita",
    category: "Grilled",
    imageUrl: "/images/menu/fajita.jpg",
    caption: "Sizzling grilled chicken strips with peppers and tortilla.",
    sortOrder: 4,
  },
  {
    title: "Tandoor Chicken Mofo",
    category: "Mofo",
    imageUrl: "/images/menu/mofo-double.jpg",
    caption: "Scored, marinated overnight and grilled in the tandoor.",
    sortOrder: 5,
  },
  {
    title: "Crispy Chicken Burgers",
    category: "Burgers",
    imageUrl: "/images/menu/burger.jpg",
    caption: "Crunchy chicken fillet, house mayo and a soft bun with fries.",
    sortOrder: 6,
  },
];
